kind = "api"
previewPath = "/"
title = "Spendly"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 3000
name = "Spendly"
paths = ["/"]

[services.development]
run = "cd artifacts/spendly && node server.js"
